---
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/vpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/eks"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/k8s-addon"
    schedule:
      interval: "daily"
